/**
 * BOMIX Backend API Service
 *
 * This module provides a unified interface for all backend API calls.
 * It wraps Wails bindings and provides consistent error handling.
 */

// Import Wails generated bindings
// Note: These will be generated by Wails when the project is built
import { Dialogs, Events } from '@wailsio/runtime'

declare global {
  interface Window {
    go: {
      bomixAppBackendApp?: {
        // Series management
        CreateSeries(path: string, name: string, description: string): Promise<void>
        OpenSeries(path: string): Promise<void>
        CloseSeries(): Promise<void>
        GetSeriesInfo(): Promise<SeriesInfo>
        GetRecentSeries(): Promise<RecentFile[]>

        // Project management
        GetProjects(seriesId: number): Promise<Project[]>
        GetProject(id: number): Promise<Project>

        // Revision management
        GetRevisions(projectId: number): Promise<BomRevision[]>
        GetRevision(id: number): Promise<BomRevision>

        // Import/Export
        ImportExcel(filePaths: string[]): Promise<ImportResult[]>
        ExportExcel(options: ExportOptions): Promise<string[]>

        // Task management
        ListTasks(): Promise<Task[]>
        GetTask(id: string): Promise<Task>
        CancelTask(id: string): Promise<void>

        // Logs
        GetLogs(level: string, limit: number): Promise<LogEntry[]>
        ClearLogs(): Promise<void>

        // Settings
        GetSettings(): Promise<Settings>
        UpdateSettings(settings: Settings): Promise<void>

        // App
        Quit(): void
        GetVersion(): string
      }
    }
  }
}

// Type definitions matching backend models
export interface SeriesInfo {
  id: number
  name: string
  description: string
  path: string
}

export interface RecentFile {
  path: string
  name: string
  lastOpened: string
}

export interface Project {
  id: number
  seriesId: number
  code: string
  description: string
  createdAt: string
  updatedAt: string
}

export interface BomRevision {
  id: number
  projectId: number
  phase: string
  version: string
  description: string
  schematicVersion: string
  pcbVersion: string
  pcaPn: string
  date: string
  mode: string
  sourceFile: string
  createdAt: string
  updatedAt: string
}

export interface Part {
  id: number
  revisionId: number
  type: string
  supplier: string
  supplierPn: string
  description: string
  location: string
  quantity: number
  cost: number
  bomStatus: string
  ccl: string
  remark: string
  createdAt: string
  updatedAt: string
}

export interface SecondSource {
  id: number
  revisionId: number
  partId: number
  supplier: string
  supplierPn: string
  description: string
  cost: number
  leadTime: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface MatrixModel {
  id: number
  revisionId: number
  modelName: string
  qty: number
  createdAt: string
  updatedAt: string
}

export interface MatrixSelection {
  id: number
  revisionId: number
  modelId: number
  partId: number
  group: string
  material: string
  selectedSupplier: string
  selectedSupplierPn: string
  isAutoSelected: boolean
  createdAt: string
  updatedAt: string
}

export interface Task {
  id: string
  name: string
  type: string
  status: string
  progress: number
  message: string
  error?: string
  createdAt: string
  updatedAt: string
}

export interface ImportResult {
  fileName: string
  format: string
  status: string
  message: string
  partsCount: number
  error?: string
}

export interface ExportOptions {
  format: string
  projectIds?: number[]
  revisionIds: number[]
  description?: string
  outputPath?: string
  outputDir?: string
  modelCountOverrides?: Record<string, number>
}

// Type alias for backend import result
export type BackendImportResult = ImportResult

export interface LogEntry {
  id?: string
  level: string
  message: string
  timestamp: string
  attrs?: Record<string, string>
}

export interface Settings {
  theme: string
  import: ImportSettings
  logger: LoggerSettings
  recentFiles: RecentFilesSettings
  autoOpenLastFile: boolean
  lastOpenedFile: string
  autoImportPreviousMatrix: boolean
}

export interface ImportSettings {
  confirmOverwrite: boolean
  autoImportPreviousMatrix: boolean
}

export interface LoggerSettings {
  level: string
  maxEntries: number
}

export interface RecentFilesSettings {
  maxRecentFiles: number
  recentFiles: string[]
}

export interface FileDialogOptions {
  title?: string
  defaultPath?: string
  filters?: FileFilter[]
  buttonLabel?: string
  selectFiles?: boolean
  selectDirectory?: boolean
  multiSelect?: boolean
}

export interface FileFilter {
  name: string
  extensions: string[]
}

// Error handling wrapper
class ApiError extends Error {
  constructor(
    public message: string,
    public code: string = 'UNKNOWN_ERROR',
    public originalError?: Error
  ) {
    super(message)
    this.name = 'ApiError'
  }
}

// Handle API errors consistently
function handleApiError(error: unknown, context: string): never {
  if (error instanceof Error) {
    throw new ApiError(
      `${context}: ${error.message}`,
      'API_ERROR',
      error
    )
  }
  throw new ApiError(
    `${context}: Unknown error`,
    'UNKNOWN_ERROR'
  )
}

// Check if Wails bindings are available
function checkWailsBindings(): void {
  if (!window.go?.bomixAppBackendApp) {
    throw new ApiError(
      'Wails backend bindings not available. Make sure the application is running.',
      'NO_BACKEND'
    )
  }
}

// ==================== Series Management ====================

export async function CreateSeries(path: string, name: string, description: string): Promise<void> {
  try {
    checkWailsBindings()
    await window.go.bomixAppBackendApp!.CreateSeries(path, name, description)
  } catch (error) {
    handleApiError(error, 'CreateSeries')
  }
}

export async function OpenSeries(path: string): Promise<void> {
  try {
    checkWailsBindings()
    await window.go.bomixAppBackendApp!.OpenSeries(path)
  } catch (error) {
    handleApiError(error, 'OpenSeries')
  }
}

export async function CloseSeries(): Promise<void> {
  try {
    checkWailsBindings()
    await window.go.bomixAppBackendApp!.CloseSeries()
  } catch (error) {
    handleApiError(error, 'CloseSeries')
  }
}

export async function GetSeriesInfo(path?: string): Promise<SeriesInfo> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetSeriesInfo()
  } catch (error) {
    handleApiError(error, 'GetSeriesInfo')
  }
}

export async function GetRecentSeries(): Promise<RecentFile[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetRecentSeries()
  } catch (error) {
    handleApiError(error, 'GetRecentSeries')
  }
}

// ==================== Project Management ====================

export async function GetProjects(seriesId: number): Promise<Project[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetProjects(seriesId)
  } catch (error) {
    handleApiError(error, 'GetProjects')
  }
}

export async function GetProject(id: number): Promise<Project> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetProject(id)
  } catch (error) {
    handleApiError(error, 'GetProject')
  }
}

// ==================== Revision Management ====================

export async function GetRevisions(projectId: number): Promise<BomRevision[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetRevisions(projectId)
  } catch (error) {
    handleApiError(error, 'GetRevisions')
  }
}

export async function GetRevision(id: number): Promise<BomRevision> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetRevision(id)
  } catch (error) {
    handleApiError(error, 'GetRevision')
  }
}

// ==================== Import/Export ====================

export async function ImportExcel(filePaths: string[]): Promise<ImportResult[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.ImportExcel(filePaths)
  } catch (error) {
    handleApiError(error, 'ImportExcel')
  }
}

export async function ExportExcel(options: ExportOptions): Promise<string[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.ExportExcel(options)
  } catch (error) {
    handleApiError(error, 'ExportExcel')
  }
}

// ==================== Task Management ====================

export async function ListTasks(): Promise<Task[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.ListTasks()
  } catch (error) {
    handleApiError(error, 'ListTasks')
  }
}

export async function GetTask(id: string): Promise<Task> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetTask(id)
  } catch (error) {
    handleApiError(error, 'GetTask')
  }
}

export async function CancelTask(id: string): Promise<void> {
  try {
    checkWailsBindings()
    await window.go.bomixAppBackendApp!.CancelTask(id)
  } catch (error) {
    handleApiError(error, 'CancelTask')
  }
}

// ==================== Logs ====================

export async function GetLogs(level: string, limit: number): Promise<LogEntry[]> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetLogs(level, limit)
  } catch (error) {
    handleApiError(error, 'GetLogs')
  }
}

export async function ClearLogs(): Promise<void> {
  try {
    checkWailsBindings()
    await window.go.bomixAppBackendApp!.ClearLogs()
  } catch (error) {
    handleApiError(error, 'ClearLogs')
  }
}

// ==================== Settings ====================

export async function GetSettings(): Promise<Settings> {
  try {
    checkWailsBindings()
    return await window.go.bomixAppBackendApp!.GetSettings()
  } catch (error) {
    handleApiError(error, 'GetSettings')
  }
}

export async function UpdateSettings(settings: Settings): Promise<void> {
  try {
    checkWailsBindings()
    await window.go.bomixAppBackendApp!.UpdateSettings(settings)
  } catch (error) {
    handleApiError(error, 'UpdateSettings')
  }
}

// ==================== Event Listening ====================

const eventListeners = new Map<string, any>()

export function ListenToEvents(eventName: string, callback: (data: any) => void): void {
  try {
    // Register with Wails v3
    const unlistener = Events.On(eventName, (e: any) => {
      // Wails v3 events pass an object { name, data: [...] }
      const data = e.data && e.data.length > 0 ? e.data[0] : e.data
      callback(data)
    })
    
    // Store unlistener to allow unregistering later
    eventListeners.set(eventName, unlistener)
  } catch (error) {
    console.error(`Failed to listen to event ${eventName}:`, error)
  }
}

export function UnlistenToEvents(eventName: string): void {
  try {
    const unlistener = eventListeners.get(eventName)
    if (unlistener) {
      unlistener()
      eventListeners.delete(eventName)
    }
  } catch (error) {
    console.error(`Failed to unlisten to event ${eventName}:`, error)
  }
}

// ==================== File Dialogs ====================

export async function OpenFileDialog(options: FileDialogOptions): Promise<string> {
  try {
    const filters = options.filters?.map(f => ({
      DisplayName: f.name,
      Pattern: f.extensions.map(ext => `*.${ext}`).join(';')
    }))

    const result = await Dialogs.OpenFile({
      Title: options.title,
      Filters: filters,
      AllowsMultipleSelection: false,
    })
    
    return Array.isArray(result) ? result[0] : (result || '')
  } catch (error) {
    handleApiError(error, 'OpenFileDialog')
  }
}

export async function SaveFileDialog(options: FileDialogOptions): Promise<string> {
  try {
    const filters = options.filters?.map(f => ({
      DisplayName: f.name,
      Pattern: f.extensions.map(ext => `*.${ext}`).join(';')
    }))

    const result = await Dialogs.SaveFile({
      Title: options.title,
      Filters: filters,
    })
    
    return result || ''
  } catch (error) {
    handleApiError(error, 'SaveFileDialog')
  }
}

export async function SelectFolderDialog(options: FileDialogOptions): Promise<string> {
  try {
    const result = await Dialogs.OpenFile({
      Title: options.title,
      CanChooseDirectories: true,
      CanChooseFiles: false,
      AllowsMultipleSelection: false,
    })
    
    return Array.isArray(result) ? result[0] : (result || '')
  } catch (error) {
    handleApiError(error, 'SelectFolderDialog')
  }
}

// ==================== App ====================

export function Quit(): void {
  try {
    checkWailsBindings()
    window.go.bomixAppBackendApp!.Quit()
  } catch (error) {
    console.error('Failed to quit application:', error)
  }
}

export function GetVersion(): string {
  try {
    checkWailsBindings()
    return window.go.bomixAppBackendApp!.GetVersion()
  } catch (error) {
    console.error('Failed to get version:', error)
    return 'unknown'
  }
}
