// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MatrixModelInput 定義更新 Revision Models 時的單一 Model 輸入資料
 */
export interface MatrixModelInput {
    "id": number;
    "sort_order": number;
    "model_name": string;
    "qty": number;
}
