// Package bindings provides Wails bindings for the application.
package bindings

// This is a placeholder file to satisfy Wails build requirements.
// The actual bindings will be generated by Wails.
