// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ViewModelSelection 某個 BOM Revision 內、某個 Model 的勾選狀態。
 * 
 * 此 struct 為 ViewPartGroup.Selections 的元素，代表在某個 revision 的
 * 某個 Model 中，此物料群組被選中的是哪顆料（主料或替代料）。
 */
export interface ViewModelSelection {
    "revision_id": number;
    "model_name": string;
    "model_qty": number;

    /**
     * 被選中的 SupplierPN（空字串=未勾選或尚未設定）
     */
    "selected_pn": string;
}

/**
 * ViewPartGroup 聚合後的物料群組，是 View 系統的核心輸出單元。
 * 
 * 物料群組的識別鍵為 (MainSupplier, MainSupplierPN)。
 * 當查詢涵蓋多個 BOM Revision 時，同一群組鍵的物料會被合併為一個
 * ViewPartGroup，其中的 SourceRevisionIDs 記錄此群組存在於哪些 revision。
 * 
 * 下游消費者（Export/Frontend）利用 SourceRevisionIDs 判斷：
 *   if revisionID ∈ part.SourceRevisionIDs → 此物料在該 revision 中存在
 *   if revisionID ∉ part.SourceRevisionIDs → 此物料在該 revision 中不存在
 *     → BigMatrix 匯出：填灰色底色
 *     → Frontend 顯示：加特殊標記
 */
export interface ViewPartGroup {
    /**
     * 群組識別鍵
     */
    "main_supplier": string;
    "main_supplier_pn": string;

    /**
     * 物料基本屬性（取自 SourceRevisionIDs 中第一份包含此物料的 revision）
     */
    "item": string;
    "hhpn": string;
    "description": string;

    /**
     * SMD, PTH, BOTTOM（空=僅狀態頁面的料）
     */
    "type": string;

    /**
     * I, X, P, M
     */
    "bom_status": string;

    /**
     * Y, N
     */
    "ccl": string;
    "remark": string;

    /**
     * 聚合結果（取自第一份有此物料的 revision）
     */
    "qty": number;

    /**
     * 逗號分隔的位置編號
     */
    "locations": string;

    /**
     * 來源歸屬：此物料群組出現在哪些 BOM Revision 中
     * 這是 View 系統的核心輸出，下游消費者依此判斷物料存在性
     */
    "source_revision_ids": number[] | null;

    /**
     * 替代料（所有 revision 的聯集，以 supplier+supplier_pn 去重）
     * 每個 ViewSecondSource 也附帶自己的 SourceRevisionIDs
     */
    "second_sources": ViewSecondSource[] | null;

    /**
     * Model 勾選狀態（跨 revision × model 的完整矩陣）
     * 包含所有被查詢的 revision 中，此物料群組的所有 model 勾選記錄
     */
    "selections": ViewModelSelection[] | null;
}

/**
 * ViewQuery 視圖查詢參數，作為查詢的完整描述。
 * 
 * 設計原則：View 系統為無狀態服務，每次呼叫時傳入完整的 ViewQuery，
 * 多個 goroutine 可同時以不同的 ViewQuery 進行查詢而不互相影響。
 * 
 * 欄位說明：
 *   - RevisionIDs：查詢目標的 BOM Revision ID 列表。
 *     傳入單個 ID → 單一 revision 視圖；
 *     傳入多個 ID → 多 revision 整合聯集視圖。
 *   - ViewType：視圖過濾類型，空字串預設為 ALL。
 *   - ModeOverride：覆蓋 revision 自身的 Mode（NPI/MP）。
 *     空字串表示由各 revision 自己的 Mode 決定；
 *     指定後，所有 revision 皆使用此 Mode 進行過濾。
 */
export interface ViewQuery {
    /**
     * 要查詢的 BOM Revision ID 列表（1個=單一視圖，多個=整合視圖）
     */
    "RevisionIDs": number[] | null;

    /**
     * 視圖類型：ALL, SMD, PTH, BOTTOM, NI, PROTO, MP, CCL
     */
    "ViewType": string;

    /**
     * 覆蓋 Mode（NPI/MP），空字串=各自使用 revision 的 Mode
     */
    "ModeOverride": string;
}

/**
 * ViewResult 視圖查詢結果，是 Service.Query() 的回傳值。
 */
export interface ViewResult {
    "query": ViewQuery;
    "part_groups": ViewPartGroup[] | null;

    /**
     * 參與查詢的 revision 元資料（保持查詢順序）
     */
    "revisions": ViewRevision[] | null;
}

/**
 * ViewRevision BOM Revision 的元資料摘要，附帶在查詢結果中。
 */
export interface ViewRevision {
    "id": number;
    "project_code": string;
    "phase": string;
    "version": string;
    "description": string;
    "schematic_version": string;
    "pcb_version": string;
    "pca_pn": string;
    "date": string;

    /**
     * NPI 或 MP
     */
    "mode": string;
    "model_names": string[] | null;

    /**
     * Model 名稱 -> 打件數量
     */
    "model_qty": { [_ in string]?: number } | null;
}

/**
 * ViewSecondSource 替代料（2nd Source）的視圖 DTO。
 * 
 * SourceRevisionIDs 記錄此替代料出現在哪些 BOM Revision 中，
 * 用於讓下游（Export/Frontend）判斷「此替代料在特定 revision 中是否存在」。
 */
export interface ViewSecondSource {
    "hhpn": string;
    "supplier": string;
    "supplier_pn": string;
    "description": string;

    /**
     * 包含此替代料的 Revision ID 列表
     */
    "source_revision_ids": number[] | null;
}
