// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info 代表應用程式完整的版本與建置元資料結構
 */
export interface Info {
    /**
     * Version 應用程式版本號
     */
    "version": string;

    /**
     * GitCommit Git Commit 雜湊碼
     */
    "gitCommit": string;

    /**
     * BuildTime 二進位檔建置時間戳
     */
    "buildTime": string;
}
