// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatMessage 對話訊息結構
 */
export interface ChatMessage {
    /**
     * "system" | "user" | "assistant" | "tool"
     */
    "role": string;

    /**
     * 訊息內文
     */
    "content": string;

    /**
     * Assistant 發出的工具呼叫請求清單
     */
    "tool_calls"?: ToolCall[] | null;

    /**
     * Tool 角色對應的呼叫 ID
     */
    "tool_call_id"?: string;

    /**
     * 函數名稱（可選）
     */
    "name"?: string;
}

/**
 * FunctionCall 工具調用的函數名稱與參數
 */
export interface FunctionCall {
    "name": string;

    /**
     * JSON 字串
     */
    "arguments": string;
}

/**
 * ToolCall LLM 回傳的工具調用結構
 */
export interface ToolCall {
    "id": string;

    /**
     * 固定為 "function"
     */
    "type": string;
    "function": FunctionCall;
}
