// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 代表 BOMIX Wails 核心應用程式橋接結構體
 * 負責管理 Wails 生命週期、底層服務依賴（DB、Logger、Config、TaskMgr）以及事件派發
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as view$0 from "./view/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../context/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AIChatFetchModelsWithConfig 支援前端使用指定的 BaseURL 與 APIKey 即時取得伺服器提供的可用模型清單
 * 
 * 參數：
 *   - baseURL: 自訂 API Base URL
 *   - apiKey: 自訂 API Key
 * 
 * 回傳：
 *   - []string: 可用模型清單
 *   - error: 若 BaseURL 為空或查詢失敗則回傳錯誤
 */
export function AIChatFetchModelsWithConfig(baseURL: string, apiKey: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3556992322, baseURL, apiKey);
}

/**
 * AIChatGetAvailableModels 透過當前設定的 BaseURL 與 APIKey 取得伺服器提供的可用模型清單
 * 
 * 回傳：
 *   - []string: 可用模型識別字串陣列
 *   - error: 若 BaseURL 為空或請求失敗則回傳錯誤
 */
export function AIChatGetAvailableModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1021659951);
}

/**
 * AIChatSend 接收前端對話歷史，以 Task 任務形式啟動 AI Agentic Loop 進行推論與查詢
 * 
 * 流程：
 * 1. 檢查 AI 設定（URL 與 Key）
 * 2. 檢查目前是否已開啟系列資料庫
 * 3. 中斷任何先前正在執行的對話任務
 * 4. 擷取使用者最後提問組成任務名稱，透過 taskMgr.Submit 派發 AIChat 任務
 * 5. 執行過程透過 taskLogger 輸出結構化日誌（自動帶 taskID 歸屬 Log Group）
 * 6. 立即回傳 nil，結果即時透過 ai:chunk / ai:tool_call / ai:tool_result / ai:done / ai:error 等事件推送
 * 
 * 參數：
 *   - messages: 完整的對話歷史紀錄
 * 
 * 回傳：
 *   - error: 若未啟用 AI、未開啟資料庫或未設定 URL 則回傳錯誤
 */
export function AIChatSend(messages: ai$0.ChatMessage[] | null): $CancellablePromise<void> {
    return $Call.ByID(3543463388, messages);
}

/**
 * AIChatStop 中斷當前正在執行的 AI 生成或工具調用
 * 
 * 回傳：
 *   - error: 固定回傳 nil
 */
export function AIChatStop(): $CancellablePromise<void> {
    return $Call.ByID(216978574);
}

/**
 * AIChatTestConnection 測試 AI 端點與 API Key 是否有效
 * 
 * 回傳：
 *   - error: 若 BaseURL 為空或遠端測試請求失敗則回傳錯誤
 */
export function AIChatTestConnection(): $CancellablePromise<void> {
    return $Call.ByID(2724738698);
}

/**
 * CancelTask 取消指定 ID 的執行中或等待中任務
 * 
 * 參數：
 *   - id: 任務 ID
 * 
 * 回傳：
 *   - error: 若取消失敗則回傳錯誤
 */
export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(600074181, id);
}

/**
 * ClearLogs 清除記憶體中的所有日誌環形緩衝區紀錄
 * 
 * 回傳：
 *   - error: 固定回傳 nil
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1213143576);
}

/**
 * CloseSeries 關閉目前已開啟的系列資料庫，並中斷所有執行中的 AI 任務
 * 
 * 回傳：
 *   - error: 若關閉資料庫失敗則回傳錯誤
 */
export function CloseSeries(): $CancellablePromise<void> {
    return $Call.ByID(772726055);
}

/**
 * ConfirmTaskOverwrite 回應指定任務的覆蓋確認請求。
 * 
 * 參數：
 *   - taskID: 任務 ID
 *   - overwrite: true 表示確認覆蓋，false 表示略過覆蓋
 * 
 * 回傳：
 *   - error: 若任務不存在或未處於等待確認狀態則回傳錯誤
 */
export function ConfirmTaskOverwrite(taskID: string, overwrite: boolean): $CancellablePromise<void> {
    return $Call.ByID(3408973748, taskID, overwrite);
}

/**
 * CopyMatrixSelections 以異步任務形式，手動將指定 source revision 的 Matrix Model 與 Selection 複製到 target revision。
 * 
 * 此函數為手動版本複製的 Wails 綁定入口，會以 Task 形式提交至背景執行，
 * 讓 UI 可透過 Task ID 追蹤執行進度與結果。
 * 
 * 參數：
 *   - sourceRevisionID: 來源版本 ID（Matrix 資料的來源）
 *   - targetRevisionID: 目標版本 ID（Matrix 資料的目的地）
 * 
 * 回傳：
 *   - string: 任務 ID（taskID），可用於前端 Task 追蹤
 *   - error: 若資料庫未開啟或 revision 不存在則回傳錯誤
 */
export function CopyMatrixSelections(sourceRevisionID: number, targetRevisionID: number): $CancellablePromise<string> {
    return $Call.ByID(453441525, sourceRevisionID, targetRevisionID);
}

/**
 * CreateSeries 在指定路徑建立新的 BOMIX 系列資料庫檔案並初始化 Schema
 * 
 * 參數：
 *   - path: 系列資料庫目標檔案路徑（如 .bomx）
 *   - name: 系列名稱
 *   - description: 系列描述
 * 
 * 回傳：
 *   - error: 若路徑建立失敗、資料庫開啟失敗或 Schema 遷移失敗則回傳錯誤
 */
export function CreateSeries(path: string, name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(2615235951, path, name, description);
}

/**
 * EmitEvent 透過 Wails 執行期環境向前端發送自訂事件
 * 
 * 參數：
 *   - event: 事件名稱（如 "task:progress", "time" 等）
 *   - data: 攜帶之資料物件
 */
export function EmitEvent(event: string, data: any): $CancellablePromise<void> {
    return $Call.ByID(2964400463, event, data);
}

/**
 * ExportExcel 依指定格式將資料庫資料匯出為 Excel 檔案
 * 
 * 支援格式：
 *   - Matrix: 針對每個選取的 Revision 分別獨立匯出一個 Matrix 檔案
 *   - BigMatrix: 將多個選取的 Revision 橫向展開合併於單一 BigMatrix 檔案
 * 
 * 參數：
 *   - options: 匯出選項參數（包含格式、選取的 RevisionIDs、覆蓋 Model 數量、輸出目錄等）
 * 
 * 回傳：
 *   - []string: 建立的背景 Task ID 列表
 *   - error: 若未開啟系列資料庫則回傳錯誤
 */
export function ExportExcel(options: $models.ExportOptions | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(3476992315, options);
}

/**
 * GetBOMView 查詢 BOM 視圖資料，是 View 系統的 Wails 綁定入口。
 * 
 * View 系統為無狀態設計，前端顯示與後端匯出可同時以不同條件查詢。
 * 
 * 參數：
 *   - revisionIDs: 要查詢的 BOM Revision ID 列表（1個=單一視圖，多個=整合視圖）
 *   - viewType: 視圖類型（ALL/SMD/PTH/BOTTOM/NI/PROTO/MP/CCL），空字串預設為 ALL
 * 
 * 回傳：
 *   - *view.ViewResult: 查詢結果，包含聚合物料群組與 revision 元資料
 *   - error: 若資料庫連線未開啟或查詢失敗則回傳錯誤
 */
export function GetBOMView(revisionIDs: number[] | null, viewType: string): $CancellablePromise<view$0.ViewResult | null> {
    return $Call.ByID(318394637, revisionIDs, viewType);
}

/**
 * GetContext 取得應用程式 Context（Wails v3 中已由內部機制管理，此處固定回傳 nil）
 * 
 * 回傳：
 *   - context.Context: 固定回傳 nil
 */
export function GetContext(): $CancellablePromise<context$0.Context> {
    return $Call.ByID(2032364409);
}

/**
 * GetDefaultSettings 取得應用程式預設配置作為 Settings DTO（單一真理來源 Single Source of Truth）
 * 
 * 回傳：
 *   - *Settings: 系統預設配置 DTO
 *   - error: 固定回傳 nil
 */
export function GetDefaultSettings(): $CancellablePromise<$models.Settings | null> {
    return $Call.ByID(3349389726);
}

/**
 * GetLogs 依層級與筆數上限查詢日誌環形緩衝區中的紀錄
 * 
 * 參數：
 *   - level: 欲過濾的最低層級（如 "DEBUG", "INFO", "WARN", "ERROR"）
 *   - limit: 最多回傳筆數
 * 
 * 回傳：
 *   - []*LogEntry: 日誌紀錄清單 DTO
 *   - error: 固定回傳 nil
 */
export function GetLogs(level: string, limit: number): $CancellablePromise<($models.LogEntry | null)[] | null> {
    return $Call.ByID(1692275157, level, limit);
}

/**
 * GetProject 依專案 ID 取得指定專案資訊
 * 
 * 參數：
 *   - id: 專案 ID
 * 
 * 回傳：
 *   - *Project: 專案資訊 DTO
 *   - error: 若未開啟系列資料庫或專案不存在則回傳錯誤
 */
export function GetProject(id: number): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(2418279407, id);
}

/**
 * GetProjects 取得目前系列中的所有專案清單
 * 
 * 參數：
 *   - seriesID: 系列 ID
 * 
 * 回傳：
 *   - []*Project: 專案清單 DTO
 *   - error: 若未開啟系列資料庫或查詢失敗則回傳錯誤
 */
export function GetProjects(seriesID: number): $CancellablePromise<($models.Project | null)[] | null> {
    return $Call.ByID(2226237076, seriesID);
}

/**
 * GetRecentSeries 傳回最近開啟的系列清單
 * 1. 若檔案不存在：清理 TOML 設定檔紀錄，不顯示在 UI
 * 2. 若檔案存在但無法開啟/讀取（格式不合或損毀）：保留 TOML 紀錄，但回傳標示 IsCorrupted = true 供 UI 顯示
 * 
 * 回傳：
 *   - []*RecentFile: 最近開啟檔案清單
 *   - error: 若讀取失敗則回傳錯誤
 */
export function GetRecentSeries(): $CancellablePromise<($models.RecentFile | null)[] | null> {
    return $Call.ByID(2788415008);
}

/**
 * GetRevision 依 Revision ID 取得指定 BOM Revision 詳細資訊
 * 
 * 參數：
 *   - id: Revision ID
 * 
 * 回傳：
 *   - *BomRevision: Revision 詳細資訊 DTO
 *   - error: 若未開啟系列資料庫或 Revision 不存在則回傳錯誤
 */
export function GetRevision(id: number): $CancellablePromise<$models.BomRevision | null> {
    return $Call.ByID(942744999, id);
}

/**
 * GetRevisions 取得指定專案的所有 BOM Revision 清單
 * 
 * 參數：
 *   - projectID: 專案 ID
 * 
 * 回傳：
 *   - []*BomRevision: Revision 清單 DTO（包含 Model 數量統計）
 *   - error: 若未開啟系列資料庫或查詢失敗則回傳錯誤
 */
export function GetRevisions(projectID: number): $CancellablePromise<($models.BomRevision | null)[] | null> {
    return $Call.ByID(1230933180, projectID);
}

/**
 * GetSeriesInfo 取得目前開啟中的系列基本資訊與匯出排序設定
 * 
 * 回傳：
 *   - *SeriesInfo: 系列詳細資訊 DTO
 *   - error: 若當前無開啟中的系列資料庫則回傳錯誤
 */
export function GetSeriesInfo(): $CancellablePromise<$models.SeriesInfo | null> {
    return $Call.ByID(2829270067);
}

/**
 * GetSettings 取得當前應用程式設定（API 金鑰將會被遮罩以確保安全）
 * 
 * 回傳：
 *   - *Settings: 當前設定 DTO
 *   - error: 固定回傳 nil
 */
export function GetSettings(): $CancellablePromise<$models.Settings | null> {
    return $Call.ByID(2031216731);
}

/**
 * GetTask 依任務 ID 取得特定背景任務的詳細資訊與進度狀態
 * 
 * 參數：
 *   - id: 任務 ID
 * 
 * 回傳：
 *   - *Task: 任務詳細資訊 DTO
 *   - error: 若任務不存在則回傳錯誤
 */
export function GetTask(id: string): $CancellablePromise<$models.Task | null> {
    return $Call.ByID(1640563699, id);
}

/**
 * GetVersion 取得目前應用程式版本號字串
 * 
 * 回傳：
 *   - string: 版本號
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1976651186);
}

/**
 * ImportExcel 依兩階段分組匯入 Excel 檔案至資料庫
 * 
 * 執行邏輯：
 * 1. 檔案分組：依檔名是否包含 "matrix" (不區分大小寫) 分為非 Matrix 組與 Matrix 組。
 * 2. 兩階段執行：
 *   - 第一階段：先背景執行非 Matrix 組 (EBOM/一般 BOM) 的匯入任務。
 *   - 第二階段：等待第一階段所有群組任務全數結束後，Matrix 組自動接續執行開檔與匯入。
 * 
 * 參數：
 *   - filePaths: 欲匯入的 Excel 檔案路徑清單
 *   - confirmOverwrite: 匯入覆蓋現有 BOM 前是否提示確認
 * 
 * 回傳：
 *   - []*ImportResult: 包含所有提交任務之 Task ID 與狀態資訊
 *   - error: 若當前無開啟中的 Series 則回傳錯誤
 */
export function ImportExcel(filePaths: string[] | null, confirmOverwrite: boolean): $CancellablePromise<($models.ImportResult | null)[] | null> {
    return $Call.ByID(882224074, filePaths, confirmOverwrite);
}

/**
 * ListTasks 取得所有背景任務清單及其最新狀態
 * 
 * 回傳：
 *   - []*Task: 任務清單 DTO
 *   - error: 固定回傳 nil
 */
export function ListTasks(): $CancellablePromise<($models.Task | null)[] | null> {
    return $Call.ByID(3322225680);
}

/**
 * LogFrontend 接收前端 UI 轉發之日誌訊息，並統一寫入後端結構化日誌系統
 * 
 * 參數：
 *   - level: 日誌層級（"DEBUG", "WARN", "ERROR", 預設為 "INFO"）
 *   - message: 日誌訊息內容
 */
export function LogFrontend(level: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1087350636, level, message);
}

/**
 * OpenSeries 開啟指定路徑的既有系列資料庫檔案
 * 
 * 參數：
 *   - path: 系列資料庫檔案路徑
 * 
 * 回傳：
 *   - error: 若檔案不存在、開啟失敗或自動遷移失敗則回傳錯誤
 */
export function OpenSeries(path: string): $CancellablePromise<void> {
    return $Call.ByID(2027733203, path);
}

/**
 * Quit 安全結束並關閉應用程式視窗與進程
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2337999657);
}

/**
 * SaveProjectExportOrder 即時儲存 BigMatrix 匯出對話框中的 Project 排序與 Model 數量設定紀錄至 Series 資料表
 * 
 * 參數：
 *   - settings: 專案匯出設定列表（包含 ProjectCode 與 ModelCount）
 * 
 * 回傳：
 *   - error: 若未開啟資料庫或 JSON 轉換/寫入失敗則回傳錯誤
 */
export function SaveProjectExportOrder(settings: $models.ProjectExportSetting[] | null): $CancellablePromise<void> {
    return $Call.ByID(156455538, settings);
}

/**
 * SetMatrixModelSelection 更新單一物料群組在指定 Revision 與 Model 排序索引 (SortOrder) 的勾選狀態。
 * 
 * 參數：
 *   - revisionID: BOM Revision ID
 *   - sortOrder: 0-based Model 排序索引 (0, 1, 2...)
 *   - mainMaterialID: 主料 Material ID
 *   - selectedMaterialID: 被選中的物料 Material ID（傳入 0 表示取消勾選）
 * 
 * 回傳：
 *   - error: 若資料庫未開啟或更新失敗則回傳錯誤
 */
export function SetMatrixModelSelection(revisionID: number, sortOrder: number, mainMaterialID: number, selectedMaterialID: number): $CancellablePromise<void> {
    return $Call.ByID(963482066, revisionID, sortOrder, mainMaterialID, selectedMaterialID);
}

/**
 * SetMatrixSelection 更新單一物料群組在指定 Revision 與 Model 的勾選狀態。
 * 
 * 參數：
 *   - revisionID: BOM Revision ID
 *   - modelID: Matrix Model ID（若為 0 則自動查找或建立預設 Model）
 *   - mainMaterialID: 主料 Material ID
 *   - selectedMaterialID: 被選中的物料 Material ID（傳入 0 表示取消勾選）
 * 
 * 回傳：
 *   - error: 若資料庫未開啟或更新失敗則回傳錯誤
 */
export function SetMatrixSelection(revisionID: number, modelID: number, mainMaterialID: number, selectedMaterialID: number): $CancellablePromise<void> {
    return $Call.ByID(2396468907, revisionID, modelID, mainMaterialID, selectedMaterialID);
}

/**
 * UpdateMaterialNote 更新指定物料的 Notes 欄位內容，並持久化至資料庫。
 * 
 * 參數：
 *   - materialID: 物料 ID (Material.ID)
 *   - notes: 新的 Notes 內容
 * 
 * 回傳：
 *   - error: 若資料庫未開啟或更新失敗則回傳錯誤
 */
export function UpdateMaterialNote(materialID: number, notes: string): $CancellablePromise<void> {
    return $Call.ByID(1908766894, materialID, notes);
}

/**
 * UpdateRevisionMatrixModels 批次更新指定 Revision 的所有 MatrixModel (包含 Model 數量與 Model Qty)。
 * 
 * 參數：
 *   - revisionID: BOM Revision ID
 *   - models: 欲更新的 Model 列表 (含 SortOrder, ModelName, Qty)
 * 
 * 回傳：
 *   - error: 若資料庫未開啟或更新失敗則回傳錯誤
 */
export function UpdateRevisionMatrixModels(revisionID: number, models: db$0.MatrixModelInput[] | null): $CancellablePromise<void> {
    return $Call.ByID(2449103669, revisionID, models);
}

/**
 * UpdateSettings 接收前端傳入之 Settings DTO，校驗有效值後更新並持久化至設定檔
 * 
 * 參數：
 *   - settings: 欲更新的設定物件
 * 
 * 回傳：
 *   - error: 若設定為空或持久化存檔失敗則回傳錯誤
 */
export function UpdateSettings(settings: $models.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(544783718, settings);
}
