// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct for Wails bindings
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../context/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTask cancels a task
 */
export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(600074181, id);
}

/**
 * ClearLogs clears all log entries
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(1213143576);
}

/**
 * CloseSeries closes the current series
 */
export function CloseSeries(): $CancellablePromise<void> {
    return $Call.ByID(772726055);
}

/**
 * CreateSeries creates a new series at the specified path
 */
export function CreateSeries(path: string, name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(2615235951, path, name, description);
}

/**
 * EmitEvent emits an event to the frontend via Wails runtime
 */
export function EmitEvent(event: string, data: any): $CancellablePromise<void> {
    return $Call.ByID(2964400463, event, data);
}

/**
 * ExportExcel exports data from the database to Excel files
 */
export function ExportExcel(options: $models.ExportOptions | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(3476992315, options);
}

/**
 * GetContext returns the application context
 */
export function GetContext(): $CancellablePromise<context$0.Context> {
    return $Call.ByID(2032364409);
}

/**
 * GetLogs returns log entries
 */
export function GetLogs(level: string, limit: number): $CancellablePromise<($models.LogEntry | null)[] | null> {
    return $Call.ByID(1692275157, level, limit);
}

/**
 * GetProject returns a specific project by ID
 */
export function GetProject(id: number): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(2418279407, id);
}

/**
 * GetProjects returns all projects in the current series
 */
export function GetProjects(seriesID: number): $CancellablePromise<($models.Project | null)[] | null> {
    return $Call.ByID(2226237076, seriesID);
}

/**
 * GetRecentSeries returns the list of recently opened series
 */
export function GetRecentSeries(): $CancellablePromise<($models.RecentFile | null)[] | null> {
    return $Call.ByID(2788415008);
}

/**
 * GetRevision returns a specific revision by ID
 */
export function GetRevision(id: number): $CancellablePromise<$models.BomRevision | null> {
    return $Call.ByID(942744999, id);
}

/**
 * GetRevisions returns all revisions for a project
 */
export function GetRevisions(projectID: number): $CancellablePromise<($models.BomRevision | null)[] | null> {
    return $Call.ByID(1230933180, projectID);
}

/**
 * GetSeriesInfo returns information about the currently open series
 */
export function GetSeriesInfo(): $CancellablePromise<$models.SeriesInfo | null> {
    return $Call.ByID(2829270067);
}

/**
 * GetSettings returns the current settings
 */
export function GetSettings(): $CancellablePromise<$models.Settings | null> {
    return $Call.ByID(2031216731);
}

/**
 * GetTask returns a specific task by ID
 */
export function GetTask(id: string): $CancellablePromise<$models.Task | null> {
    return $Call.ByID(1640563699, id);
}

/**
 * GetVersion returns the application version
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1976651186);
}

/**
 * ImportExcel imports Excel files into the database
 */
export function ImportExcel(filePaths: string[] | null): $CancellablePromise<($models.ImportResult | null)[] | null> {
    return $Call.ByID(882224074, filePaths);
}

/**
 * ListTasks returns all tasks
 */
export function ListTasks(): $CancellablePromise<($models.Task | null)[] | null> {
    return $Call.ByID(3322225680);
}

/**
 * LogFrontend allows the frontend to send logs to the backend logger
 */
export function LogFrontend(level: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1087350636, level, message);
}

/**
 * OpenSeries opens an existing series at the specified path
 */
export function OpenSeries(path: string): $CancellablePromise<void> {
    return $Call.ByID(2027733203, path);
}

/**
 * Quit quits the application
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2337999657);
}

/**
 * UpdateSettings updates the settings
 */
export function UpdateSettings(settings: $models.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(544783718, settings);
}
