// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BomRevision represents a BOM revision for the frontend
 */
export interface BomRevision {
    "id": number;
    "projectId": number;
    "phase": string;
    "version": string;
    "description": string;
    "schematicVersion": string;
    "pcbVersion": string;
    "pcaPn": string;
    "date": string;
    "mode": string;
    "sourceFile": string;
    "modelCount": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ExportOptions represents export options for the frontend
 */
export interface ExportOptions {
    "format": string;
    "projectIds": number[] | null;
    "revisionIds": number[] | null;
    "description"?: string;
    "outputPath"?: string;
    "outputDir"?: string;
    "modelCountOverrides"?: { [_ in string]?: number } | null;
}

/**
 * ImportResult represents an import result for the frontend
 */
export interface ImportResult {
    "fileName": string;
    "format": string;
    "status": string;
    "message": string;
    "partsCount": number;
    "error"?: string;
    "taskID"?: string;
}

/**
 * ImportSettings represents import settings for the frontend
 */
export interface ImportSettings {
    "confirmOverwrite": boolean;
    "autoImportPreviousMatrix": boolean;
}

/**
 * LogEntry represents a log entry for the frontend
 */
export interface LogEntry {
    "id"?: string;
    "level": string;
    "message": string;
    "timestamp": string;
    "attrs"?: { [_ in string]?: string } | null;
}

/**
 * LoggerSettings represents logger settings for the frontend
 */
export interface LoggerSettings {
    "level": string;
    "maxEntries": number;
}

/**
 * Project represents a project for the frontend
 */
export interface Project {
    "id": number;
    "seriesId": number;
    "code": string;
    "description": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * RecentFile represents a recently opened file
 */
export interface RecentFile {
    "path": string;
    "name": string;
    "lastOpened": string;
}

/**
 * RecentFilesSettings represents recent files settings for the frontend
 */
export interface RecentFilesSettings {
    "maxRecentFiles": number;
    "recentFiles": string[] | null;
}

/**
 * SeriesInfo represents the series information for the frontend
 */
export interface SeriesInfo {
    "id": number;
    "name": string;
    "description": string;
    "path": string;
}

/**
 * Settings represents the application settings for the frontend
 */
export interface Settings {
    "theme": string;
    "import": ImportSettings | null;
    "logger": LoggerSettings | null;
    "recentFiles": RecentFilesSettings | null;
    "autoOpenLastFile": boolean;
    "lastOpenedFile": string;
    "autoImportPreviousMatrix": boolean;
}

/**
 * Task represents a task for the frontend
 */
export interface Task {
    "id": string;
    "name": string;
    "type": string;
    "status": string;
    "progress": number;
    "message": string;
    "error"?: string;
    "createdAt": string;
    "updatedAt": string;
}
